# Generated by Django 5.0.6 on 2024-07-01 04:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zenia_app_root_geometries_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessagePromptModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_body", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
