# Generated by Django 5.0.6 on 2024-07-18 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zenia_app_root_geometries_management', '0002_messagepromptmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardModelUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stl_file_upload', models.FileField(upload_to='home/zenia_user/zenia/threedmodels/modification/')),
            ],
        ),
    ]
