# Generated by Django 5.0.6 on 2024-07-18 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zenia_app_root_geometries_management', '0003_cardmodelupload'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CardModelUpload',
            new_name='CadModelUpload',
        ),
    ]
